#!/bin/bash

command -v recode >/dev/null 2>&1 || { echo >&2 "Package dependency \"recode\" isn\'t installed. You can install it using \"sudo apt-get install recode\"."; exit 1; }

git add .;

username=$(git config user.name);
email=$(git config user.email);

read -p "Enter the username to be spoofed:" spoofas;

before="mailto:";
after="\"";
content=$(wget "https://github.com/$spoofas" -q -O -);

if [[ $content == *"$before"* ]];
then
    spoofasemail=$(echo $content | recode html/.. | grep -EiEio '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b' | head -1);
    echo "Enter the email of $spoofas:$spoofasemail";
else
    read -p "Enter the email of $spoofas:" spoofasemail;
fi;

read -p "Enter a commit message:" message;

git config user.name "$spoofas";
git config user.email "$spoofasemail";

git commit -m "$message";

git config user.name "$username";
git config user.email "$email";
